name: CoGuard Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install CoGuard CLI
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<81" coguard-cli

      - name: Create CoGuard authentication file
        run: |
          mkdir -p ~/.coguard
          echo "${{ secrets.COGUARD_EMAIL }}" > ~/.coguard/auth_file
          echo "${{ secrets.COGUARD_PASSWORD }}" >> ~/.coguard/auth_file

      - name: Run CoGuard Scan
        run: coguard scan